# Generated by Django 5.0.6 on 2024-07-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_filled',
        ),
        migrations.AddField(
            model_name='profile',
            name='target',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=128, null=True),
        ),
    ]
