# Generated by Django 5.0.6 on 2024-07-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_blood_test_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
