# Generated by Django 5.0.6 on 2024-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='injuries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_limit',
            field=models.CharField(blank=True, choices=[('onemonth', 'In one month'), ('twoweek', 'In two weeks'), ('twomonth', 'In two months'), ('sixmonth', 'In six months')], max_length=128, null=True),
        ),
    ]
