# Generated by Django 5.0.6 on 2024-07-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='type',
            field=models.CharField(choices=[('nutritionist', 'Nutritionist Doctor'), ('dietitian', 'Dietitian Doctor'), ('fitness', 'Fitness Instructor')], max_length=20),
        ),
    ]
