# Generated by Django 5.0.6 on 2024-07-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='type',
            field=models.CharField(choices=[('nutritionist', 'Nutritionist Doctor'), ('dietitian', 'Dietitian Doctor'), ('acupuncturists', 'Acupuncturists Doctor'), ('homeopaths', 'Homeopaths Doctor'), ('naturopaths', 'Naturopaths Doctor')], max_length=20),
        ),
    ]
