# Generated by Django 5.0.6 on 2024-07-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_target'),
        ('suggestions', '0002_alter_suggestion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breakfast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_recommendations', to='suggestions.food')),
                ('dinner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_recommendations', to='suggestions.food')),
                ('lunch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_recommendations', to='suggestions.food')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
