# Generated by Django 5.0.6 on 2024-07-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_food_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('avatar', models.ImageField(upload_to='stars/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StarFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_stars', to='suggestions.food')),
                ('dinner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_stars', to='suggestions.food')),
                ('lunch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_stars', to='suggestions.food')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestions.star')),
            ],
        ),
        migrations.CreateModel(
            name='StarSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_body_part_type', models.CharField(choices=[('hand', 'Hand'), ('leg', 'Leg'), ('back', 'Back'), ('chest', 'Chest'), ('ass', 'Ass')], max_length=52)),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='sports/')),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestions.star')),
            ],
        ),
    ]
