# Generated by Django 5.0.6 on 2024-07-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_injuries_profile_time_limit'),
        ('suggestions', '0004_star_starfood_starsport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starsport',
            name='fitness_body_part_type',
            field=models.CharField(choices=[('hand', 'Hand'), ('leg', 'Leg'), ('back', 'Back'), ('chest', 'Chest'), ('press', 'Press')], max_length=52),
        ),
        migrations.CreateModel(
            name='ProfileSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fitness_body_part_type', models.CharField(choices=[('hand', 'Hand'), ('leg', 'Leg'), ('back', 'Back'), ('chest', 'Chest'), ('press', 'Press')], max_length=52)),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='profile_sports/')),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
