# Generated by Django 5.0.6 on 2024-07-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_alter_starsport_fitness_body_part_type_profilesport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_sports/'),
        ),
        migrations.AlterField(
            model_name='profilesport',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
